when:
  branch: master
  event: push

steps:
  # Step 1: Build notification
  - name: notify-start
    image: alpine:latest
    commands:
      - "echo Starting MRadio deployment pipeline..."
      - "echo Branch: ${CI_COMMIT_BRANCH}"
      - "echo Commit: ${CI_COMMIT_SHA}"
      - "echo Author: ${CI_COMMIT_AUTHOR}"

  # Step 2: Deploy
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: 
        from_secret: host
      username: 
        from_secret: username
      key:
        from_secret: ssh_private_key
      port:
        from_secret: ssh_port
      command_timeout: 5m
      script:
        - "echo Connected to Oracle Cloud server"
        - "cd /home/ubuntu/docker/radio"
        - "chmod +x run.sh"
        - "./run.sh radio-main"

  # Step 4: Health check
  - name: health-check
    image: curlimages/curl:latest
    commands:
      - "sleep 10"
      - "echo 🏥 Performing health check..."
      - "curl -f https://radio.mity.in/ || echo ⚠️ Service not responding yet"

  # Step 5: Success notification
  - name: notify-success
    image: alpine:latest
    commands:
      - "echo ✅ Deployment successful!"
      - "echo 🎵 MRadio is now live at https://icecast.mity.in/radio.mp3"
    when:
      status: success

  # Step 6: Failure notification
  - name: notify-failure
    image: alpine:latest
    commands:
      - "echo ❌ Deployment failed!"
      - "echo Please check the logs above for errors"
    when:
      status: failure
