when:
  branch: master
  event: push

steps:
  # Step 1: Build notification
  - name: notify-start
    image: alpine:latest
    commands:
      - "echo Starting MRadio deployment pipeline..."
      - "echo Branch: ${CI_COMMIT_BRANCH}"
      - "echo Commit: ${CI_COMMIT_SHA}"
      - "echo Author: ${CI_COMMIT_AUTHOR}"

  # Step 2: Deploy
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: 
        from_secret: ORACLE_HOST
      username: 
        from_secret: ORACLE_USERNAME
      key:
        from_secret: ORACLE_KEY
      port:
        from_secret: ORACLE_PORT
      command_timeout: 5m
      script:
        - "echo Connected to Oracle Cloud server"
        - "cd /home/ubuntu/docker/radio"
        - "chmod +x run.sh"
        - "./run.sh radio-main"

  # Step 3: Health check
  - name: health-check
    image: curlimages/curl:latest
    commands:
      - "sleep 10"
      - "echo 🏥 Performing health check..."
      - "curl -f https://radio.mity.in/ || echo ⚠️ Service not responding yet"

  # Step 4: Success notification to Gotify
  - name: notify-success
    image: curlimages/curl:latest
    commands:
      - |
        echo "Sending success notification to Gotify..."
        curl -X POST "$${GOTIFY_URL}/message?token=$${GOTIFY_TOKEN}" \
        -F "title=✅ MRadio Deployment Success" \
        -F "message=Branch: ${CI_COMMIT_BRANCH}
        Commit: ${CI_COMMIT_SHA:0:7}
        Author: ${CI_COMMIT_AUTHOR}
        
        🎵 MRadio is now live at https://icecast.mity.in/radio.mp3" \
        -F "priority=5"
    environment:
      GOTIFY_URL:
        from_secret: gotify_url
      GOTIFY_TOKEN:
        from_secret: gotify_token
    when:
      status: success

  # Step 5: Failure notification to Gotify
  - name: notify-failure
    image: curlimages/curl:latest
    commands:
      - |
        echo "Sending failure notification to Gotify..."
        curl -X POST "$${GOTIFY_URL}/message?token=$${GOTIFY_TOKEN}" \
        -F "title=❌ MRadio Deployment Failed" \
        -F "message=Branch: ${CI_COMMIT_BRANCH}
        Commit: ${CI_COMMIT_SHA:0:7}
        Author: ${CI_COMMIT_AUTHOR}
        
        Pipeline failed. Please check logs." \
        -F "priority=10"
    environment:
      GOTIFY_URL:
        from_secret: gotify_url
      GOTIFY_TOKEN:
        from_secret: gotify_token
    when:
      status: failure
