services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9126:9126"
    volumes:
      - .:/usr/src/app
      - ./logs:/usr/src/app/logs
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
      FFMPEG_ENV: production
      TZ: Asia/Kolkata
      LOG_LEVEL: ${LOG_LEVEL:-info}
      X_ADMIN_API_KEY: ${X_ADMIN_API_KEY}
      X_ADMIN_TOKEN_KEY: ${X_ADMIN_TOKEN_KEY}
      SPOTIFY_CLIEND_ID: ${SPOTIFY_CLIEND_ID}
      SPOTIFY_CLIEND_SECRET_ID: ${SPOTIFY_CLIEND_SECRET_ID}
      SOUNDCLOUD_API_KEY: ${SOUNDCLOUD_API_KEY}
      INITIAL_PLAYLIST_ID: ${INITIAL_PLAYLIST_ID}
      INITIAL_PLAYLIST_SOURCE: ${INITIAL_PLAYLIST_SOURCE}
      INITIAL_PLAYLIST_TITLE: ${INITIAL_PLAYLIST_TITLE}
      ICECAST_HOST: ${ICECAST_HOST:-}
      ICECAST_PORT: ${ICECAST_PORT:-}
      ICECAST_PASSWORD: ${ICECAST_PASSWORD:-}
      ICECAST_MOUNT: ${ICECAST_MOUNT:-/radio.mp3}
      ICECAST_NAME: ${ICECAST_NAME:-MRadio}
      ICECAST_DESCRIPTION: ${ICECAST_DESCRIPTION:-MRadio - Multi-platform Music Streaming}
      ICECAST_GENRE: ${ICECAST_GENRE:-Various}
      ICECAST_BITRATE: ${ICECAST_BITRATE:-128}
    dns:
      - 8.8.8.8
      - 8.8.4.4
    command: npm start
